### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by migueldelamo** [4GeeksAcademy/STToDo-List-fectch#1]
Estas dos líneas hacen lo mismo. En lugar de incluir un fetch dentro de useEffect, llama a la función getTaskLists dentro del useEffect, y en la función de getTasksList, haz la gestión del error 404 tal como lo haces en el useEffect.
https://github.com/4GeeksAcademy/STToDo-List-fectch/blob/a378133f6396ef6dfb38812cbb5b132514885de0/src/js/component/Todolist.jsx#L12-L40
y https://github.com/4GeeksAcademy/STToDo-List-fectch/blob/a378133f6396ef6dfb38812cbb5b132514885de0/src/js/component/Todolist.jsx#L44

**Comment by StevenSanz** [comment]
Todo fixeado :)
